package events

const (
	CREATE_GUILD          = "CREATE_GUILD"
	DELETE_GUILD          = "DELETE_GUILD"
	UPDATE_GUILD          = "UPDATE_GUILD"
	UPDATE_GUILD_SETTINGS = "UPDATE_GUILD_SETTINGS"
	JOIN_GUILD            = "JOIN_GUILD"

	NOT_OWNER = "NOT_OWNER" //changes owner (removes old)
	NEW_OWNER = "NEW_OWNER" //changes owner (gives new)

	CREATE_INVITE = "CREATE_INVITE"
	DELETE_INVITE = "DELETE_INVITE"

	CREATE_MESSAGE       = "CREATE_MESSAGE"
	DELETE_MESSAGE       = "DELETE_MESSAGE"
	UPDATE_MESSAGE       = "UPDATE_MESSAGE"
	CLEAR_USER_MESSAGES  = "CLEAR_USER_MESSAGES"
	CLEAR_GUILD_MESSAGES = "CLEAR_GUILD_MESSAGES"
	USER_TYPING          = "USER_TYPING"

	ADD_USER_GUILDLIST    = "ADD_USER_GUILDLIST"
	UPDATE_USER_GUILDLIST = "UPDATE_USER_GUILDLIST"
	REMOVE_USER_GUILDLIST = "REMOVE_USER_GUILDLIST"
	ADD_USER_BANLIST      = "ADD_USER_BANLIST"
	REMOVE_USER_BANLIST   = "REMOVE_USER_BANLIST"

	LOG_OUT = "LOG_OUT"

	UPDATE_USER_INFO = "UPDATE_USER_INFO"
)
